company/urls.py
from django.urls import path
from company import views

urlpatterns = [
    path(
        route='mdfy_usr/<company_id>', 
        view=views.modify_user, 
        name='user_detail'
    ),
    path(
        route='position/<company_id>', 
        view=views.modify_position, 
        name='position_detail'
    ),
    path(
        route='rslts/<company_id>', 
        view=views.test_results_list, 
        name='test_results_list'
    ),

]

dpe_app/urls.py
"""dpe_app URL Configuration"""
#Django.
from django.contrib import admin
from django.urls import path, include
#Apps.
from dpe_app import views as dpe_views
from company import views as company_views
from company import views as company_views
from tests import views as tests_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('users/',include(('users.urls','users'), namespace='users')),
    path('company/',include(('company.urls','company'), namespace='company')),
    path('tests/', include('tests.urls')),
    path(
        route='dsh', 
        view=dpe_views.dashboard, 
        name='dashboard'
    ),
    path(
        route='cmp', 
        view=company_views.company_list, 
        name='companies'
    ),
    path(
        route='cmp/dtl/<company_id>/', 
        view=company_views.company_detail, 
        name='company_detail'
    ),
    path(
        route='cmp/dtl/<company_id>/<tab>', 
        view=company_views.company_detail, 
        name='company_detail'
    ),
    path(
        route='pstn',
        view=dpe_views.position_list,
        name='positions'
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path(
        route='',
        view=views.login_view, 
        name='login'
    ),
    path(
        route='admn',
        view=views.users_adm,
        name='users_admn'
    ),
    path(
        route='logout',
        view=views.log_out, 
        name='logout'
    ),
]

company/models.py
#Django.
from django.db import models
from django.urls import reverse
from datetime import date
#Models.
from users.models import User

class Company(models.Model):
    """
    Companies Model.
    """

    COMPANY_TYPE = [
        ('MAIN', 'Main'),
        ('BRANCH', 'Branch'),
    ]


    company_type = models.CharField(max_length=10,choices=COMPANY_TYPE,default='MAIN')
    company_name = models.CharField(max_length=255, blank=True)
    company_contact = models.CharField(max_length=255, blank=True)
    company_phone = models.CharField(max_length=255, blank=True)
    company_email = models.CharField(max_length=255, blank=True)
    # The id of the company this company belongs to, in case this is a sub company or branch
    company_main = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.company_name}, {self.company_type}"

class TestCatalog(models.Model):
    """ Catalog for Tests. """

    TEST_TYPE = [
        ('CIE', 'CIE'),
        ('Integridad' , 'Integridad'),
        ('Max' , 'Max'),
    ]

    test_name = models.CharField( max_length=128, choices=TEST_TYPE, null=False, blank=False)
    active = models.BooleanField( null=False, blank=False, default=True)

    def __str__(self):
        return f"{self.test_name}: ACTIVATE - {self.active}"


class TestCode(models.Model):
    """Test codes model."""
    
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    test = models.ForeignKey(TestCatalog, on_delete=models.CASCADE)
    code = models.CharField(max_length=60)
    creation = models.DateTimeField(auto_now_add=True)
    activate = models.BooleanField(default=True)
    expiration = models.DateField(null=True,blank=True)
    seconds_integrity = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.company}, {self.test}"

    @property
    def is_expired(self):
        return date.today() > self.expiration

    @property
    def get_formated_exp(self):
        return self.expiration.strftime('%d/%m/%Y')
        
    @property
    def get_minutes(self):
        if self.seconds_integrity:
            m, s = divmod(self.seconds_integrity, 60)
            if s == 0: s = '00'
            minutes = f'{m}:{s}'
            return minutes
        else:
            return '-'

class CompanyTest(models.Model):
    """
    Model to make the relation between the companies and their asigned tests.
    """
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    test = models.ForeignKey(TestCatalog, on_delete=models.CASCADE)

company/forms.py
#Django.
from django import forms
#Models.
from company.models import Company, TestCode,CompanyTest

class NewCompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('company_type','company_main','company_name','company_contact','company_phone','company_email')

    # def clean_company_main(self):
    #     """Company main (for branch companies) must be int"""
    #     company_main = self.cleaned_data['company_main']
    #     print('company main', company_main)
    #     if company_main.is_integer():
    #         return company_main
    #     else:
    #         raise forms.ValidationError('Company main not an integer')


class TestCodeForm(forms.ModelForm):

    class Meta:
        model = TestCode
        fields = ['user' ,'company' ,'test' ,'code' ,'activate' ,'expiration','seconds_integrity' ]



class CompanyTestForm(forms.ModelForm):

    class Meta:
        model = CompanyTest
        fields = ['company', 'test']

company/views.py
#Django.
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.db.models import Q
from datetime import datetime, date
from django.http import HttpResponseRedirect
from django.http import HttpResponse
#Models.
from company.models import Company, TestCode, CompanyTest, TestCatalog
from users.models import User
from tests.models import ObjectCIE, ObjectIntegrity, ObjectMax, MaxPositions
#Forms
from company.forms import NewCompanyForm, TestCodeForm, CompanyTestForm
from users.forms import SignUpForm
from users.models import User
#Utils
from company.utils import get_integrity_export_data
#Libraries
from openpyxl import Workbook
from openpyxl.writer.excel import save_virtual_workbook

@login_required
@never_cache
def company_list(request):
    """ List all available companies."""
    print("company_list")
    companies = ''
    if request.method == 'POST':
        action = request.POST.get('action','')
        #Company selected.
        if action == "select":
            company = request.POST['company']
            if company != "" and company != 0:
                return redirect('company_detail' , company_id=company)
        #Create a company.
        elif action == "create":
            print('create')
            # Get allcomapnies.
            companies = Company.objects.all().order_by('modified')
            main_companies = Company.objects.filter(company_type='MAIN')
            if request.POST.get('company_type') == 'MAIN':
                company_form = NewCompanyForm({'company_type':request.POST.get('company_type'),
                                                'company_name':request.POST.get('company_name'),
                                                'company_contact':request.POST.get('company_contact'),
                                                'company_phone':request.POST.get('company_phone'),
                                                'company_email':request.POST.get('company_email')})
            else:
                company_form = NewCompanyForm(request.POST)
            if company_form.is_valid():
                print('valid form')
                new_company = company_form.save()
                

            return render(request,'company/companies.html', {
                                                                'companies':companies,
                                                                'saved_company':'True',
                                                                'new_company':new_company,
                                                                'main_companies':main_companies,
                                                                'user': request.user
                                                            })
    elif request.method == 'GET':
        # Get user.
        user = request.user

        # Get main company and also companies that belongs to the client 
        if user.type == User.Types.CLIENT_MAIN:
            companies = Company.objects.filter(Q(id=user.company.id) | Q(company_main=user.company.id)).order_by('modified')
        # If a sub client, get only it's own company
        elif user.type == User.Types.CLIENT:
            companies = Company.objects.filter(id=user.company.id).order_by('modified')
        # Get main companies.
        elif user.type == User.Types.ADMIN_DPE:
            companies = Company.objects.all().order_by('modified')


        return render(request,'company/companies.html', {
                                                            'companies':companies,
                                                            'saved_company':'False',
                                                            'main_companies':companies.filter(company_type='MAIN'),
                                                            'user': request.user
                                                        })

@login_required
@never_cache
def company_detail(request,company_id,tab='tests'):
    """ Company detail and actions."""

    user = request.user
    
    # Get each companies details according to the user type
    if user.type == User.Types.CLIENT_MAIN:
        # Get selected company and all sub companies data.
        companies = Company.objects.filter(Q(id=user.company.id) | Q(company_main=user.company.id))
        # Get company and codes data.
        selected_company = Company.objects.get(id=company_id)
        #If company main, then this is a MAIN company
        if selected_company.company_main:
            # Get all users from Main and sub companies.
            company_users = User.objects.filter(Q(company=company_id) | Q(company_main=company_id))
            # Set the company main id to false since this is a Main company
            company_main = False
            # Get all codes from this company.
            #company_codes = TestCode.objects.filter(company__in=companies)
            company_codes = TestCode.objects.filter(company=selected_company)
        #Else, this is a sub company
        else:
            # Get just users from this sub company.
            company_users = User.objects.filter(Q(company=company_id))
            # Get the main company data for this sub company.
            company_main = selected_company.company_main
            # Get codes for just this company.
            company_codes = TestCode.objects.filter(company=selected_company)

    elif user.type == User.Types.CLIENT:
        # If a sub client, get only it's own company.
        companies = Company.objects.filter(id=user.company.id)
        # Get company and codes data.
        selected_company = Company.objects.get(id=company_id)
        # Get just users from this sub company.
        company_users = User.objects.filter(Q(company=company_id))
        # Get the main company data for this sub company.
        company_main = selected_company.company_main
        # Get codes for just this company.
        company_codes = TestCode.objects.filter(company=selected_company)

    elif user.type == User.Types.ADMIN_DPE:
        # Get company and codes data.
        selected_company = Company.objects.get(id=company_id)
        # If selected company is a main company, get its data
        companies = Company.objects.filter(Q(id=selected_company.id) | Q(company_main=selected_company.id))
        # Get just users from this sub company.
        company_users = User.objects.filter(Q(company=selected_company.id) | Q(company_main=selected_company.id))
        # Get the main company data.
        company_main = selected_company.company_main
        # Get all codes from this company companies.
        company_codes = TestCode.objects.filter(company=selected_company)

    # GET ASSIGNED TESTS FOR THIS COMPANY
    assigned_tests = CompanyTest.objects.filter(company=selected_company)
    # GET AVAILABLE TEST (EXCLUDING THE TEST THAT ARE ALREADY ASSIGNED TO THIS COMPANY)
    available_tests = TestCatalog.objects.exclude(test_name__in=[test.test.test_name for test in assigned_tests])
    # Get the max positions for this company
    max_positions = MaxPositions.objects.filter(company=selected_company)
    # Get optional return tab from POST or GET.
    if request.POST.get('tab'):
        tab = request.POST.get('tab')

    if request.method == 'POST':
        # UPDATE COMPANY 
        if request.POST.get('update'):
            print('update', selected_company)
            selected_company.company_name = request.POST.get('company_name')
            selected_company.company_contact = request.POST.get('company_contact')
            selected_company.company_email = request.POST.get('company_email')
            selected_company.save()

            return render(request,'company/company_detail.html', {
                                                                "company":selected_company,
                                                                "company_main":company_main,
                                                                "company_users":company_users,
                                                                "companies": companies,
                                                                "company_codes":company_codes,
                                                                'user': user,
                                                                'assigned_tests':assigned_tests,
                                                                'available_tests':available_tests,
                                                                'max_positions':max_positions,
                                                                'tab':'company',
                                                                })

        # CREATE COMPANY USER 
        elif request.POST.get('create_user'):
            print('create_user')
            form = SignUpForm(request.POST)
            print('form.errors > ',form.errors)
            if form.is_valid():
                form.save()
                
            return render(request,'company/company_detail.html', {
                                                                "company":selected_company,
                                                                "company_main":company_main,
                                                                "company_users":company_users,
                                                                "companies": companies,
                                                                "company_codes":company_codes,
                                                                'user': user,
                                                                'assigned_tests':assigned_tests,
                                                                'available_tests':available_tests,
                                                                'form_errors':form.errors,

templates/company/companies.html
{% extends "common/base.html" %}

{% block content_title %}
    <title>DPE - Empresas</title>
{% endblock%}

{% block content_subtitle %}
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="fas fa-building icon-gradient bg-night-fade">
                    </i>
                </div>
                <div>
                    Empresas
                    <div class="page-title-subheading">
                        Seleccione una empresa para comenzar.
                    </div>
                </div>
            </div>   
        </div>
    </div> 
{% endblock%}

{% block content_container %}
<div class="row">

    <div class="col-md-12 col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-header-tab card-header">
                <div class="btn-actions-pane-left">
                    <div class="nav">
                        <a id="search" href="javascript:void(0);" class="border-0 btn-pill btn-wide btn-transition active btn btn-outline-alternate" onclick="toogleForm(this)">Buscar</a>
                        {% if user.type == "ADMIN_DPE" %}
                            <a id="create" href="javascript:void(0);" class="ml-1 btn-pill btn-wide border-0 btn-transition  btn btn-outline-alternate second-tab-toggle-alt" onclick="toogleForm(this)">Crear</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card-body">
                {% comment %} SELECT A COMPANY {% endcomment %}
                <div id="search-form-id" class="form-container">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Tipo</th>
                            <th>Pertence a</th>
                            <th>Ultima Modificacion</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for company in companies %}
                            <tr>
                                <td>{{ company.company_name }}</td>
                                <td>
                                    {% if company.company_type == 'MAIN' %}
                                        Matriz
                                    {% else %}
                                        Sucursal
                                    {% endif %}    
                                </td>
                                <td>
                                    {% if company.company_main %}
                                        {{ company.company_main.company_name }}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>{{ company.modified }}</td>
                                <td>
                                    <form method="POST"  class="">
                                        {% csrf_token %} 
                                            <button type="submit" class="btn btn-primary btn-sm">  Ir  </button>
                                            <input type="hidden" name="action" value="select">
                                            <input type="hidden" name="company" value={{company.id}}>
                                        </div>
                                    </form>
                                </td>
                            </tr>    
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% comment %} CREATE A COMPANY {% endcomment %}
                <div id="create-company-id" class="form-container d-none">
                    <form method="POST"  >
                        {% csrf_token %}
                        <h5 class="card-title">Tipo:</h5>
                        <div class="form-row">
                            <div class="col-md-4">
                                <select name="company_type" id="company-type-id" class="form-control" onchange="typeSelected(this)">
                                    <option value="MAIN" selected >Matriz</option>
                                    <option value="BRANCH">Sucursal</option>
                                </select>   
                            </div>
                            <div class="col-md-4">
                                <select name="company_main" id="main-company-id" class="form-control d-none">
                                    <option value=0>--</option>
                                    {% for company in main_companies %}
                                        <option value={{company.id}}>{{company.company_name}}</option>                                                                                
                                    {% endfor %}
                                </select>   
                            </div>
                        </div>
                        <br>
                        <h5 class="card-title">Datos generales:</h5>
                        <div class="form-row">
                            <div class="col-md-3">
                                    <div class="position-relative form-group">
                                        <label for="company-name-id" class="">Empresa</label>
                                        <input name="company_name" id="company-name-id" type="text" class="form-control" value="" required>
                                    </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-3">
                                    <div class="position-relative form-group">
                                        <label for="company-contact-id" class="">Nombre contacto</label>
                                        <input name="company_contact" id="company-contact-id" type="text" class="form-control" value="" required>
                                    </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="position-relative form-group">
                                    <label for="company-phone-id" class="">Telefono</label>
                                    <input name="company_phone" id="company-phone-id" type="text" class="form-control" value="" required>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    <label for="company-email-id" class="">Email</label>
                                    <input name="company_email" id="company-email-id" placeholder="" type="email" class="form-control" value="" required>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="action" value="create">
                        <button class="mt-2 btn btn-primary">Crear</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    let forms = '';
    let buttons = '';
    document.addEventListener("DOMContentLoaded", function(e) {
        forms = document.querySelectorAll('.form-container');
        buttons = document.querySelectorAll('.btn-pill');

        // if a company was successfully added, show message:
        let saved_company = '{{saved_company}}'
        if ( saved_company == 'True' ){
            let company_name = '{{ new_company.company_name }}'
            showSwal('success', 'Empresa agregada', `${company_name}`, '');
        }
    });
    
    function toogleForm(btn){
        forms.forEach((form) => {
            let form_id = form.id;
            if (form_id.includes(btn.id) && form.classList.contains('d-none')){
                form.classList.remove('d-none');
            }else if (!form_id.includes(btn.id) && !form.classList.contains('d-none')){
                form.classList.add('d-none');
            }

            if(!btn.classList.contains('active')){
                btn.classList.add('active');
            }else{
                btn.classList.remove('active');
            }
        });

        buttons.forEach((btn) => {

            if(!btn.classList.contains('active')){
                btn.classList.add('active');
            }else{
                btn.classList.remove('active');
            }
        });
    }

    function typeSelected(select_element) {
        if (select_element.value == 'BRANCH') {
            document.getElementById('main-company-id').classList.remove('d-none');
        }else{
            document.getElementById('main-company-id').classList.add('d-none');
        }
    }
    

    
</script>
{% endblock%}

templates/company/user_detail.html
{% extends "common/base.html" %}

{% block content_title %}
    <title>DPE - Detalle Usuario</title>
{% endblock%}

{% block content_subtitle %}
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="fas fa-building icon-gradient bg-night-fade">
                    </i>
                </div>
                <div>
                    {{ company.company_name }}
                    <div class="page-title-subheading">
                        Administracion de Pruebas Psicometricas.
                    </div>
                </div>
            </div>   
        </div>
    </div> 
{% endblock%}

{% block content_container %}
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="main-card mb-3 card">
            <div class="card-body">

                {% comment %} MODIFY COMPANY USER {% endcomment %}
                <div id="create-form-id" class="card-section">
                    <form method="POST" action="{% url 'company:user_detail' company.id %}" class="">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-md-3">
                                <div class="position-relative form-group">
                                    <label for="username-id" class="">Nombre de usuario</label>
                                    <input name="username" id="username-id" type="text" class="form-control" value="{{selected_user.username}}">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-3">
                                    <div class="position-relative form-group">
                                        <label for="name-id" class="">Nombre</label>
                                        <input name="first_name" id="name-id" type="text" class="form-control" value="{{selected_user.first_name}}">
                                    </div>
                            </div>
                            <div class="col-md-3">
                                    <div class="position-relative form-group">
                                        <label for="last-name-id" class="">Paterno</label>
                                        <input name="last_name" id="last-name-id" type="text" class="form-control" value="{{selected_user.last_name}}">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="position-relative form-group">
                                        <label for="second-last-name-id" class="">Materno</label>
                                        <input name="second_last_name" id="second-last-name-id" type="text" class="form-control" value="{{selected_user.second_last_name}}">
                                    </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-3">
                                <div class="position-relative form-group">
                                    <label for="email-id" class="">Email</label>
                                    <input name="email" id="email-id" type="email" class="form-control" value="{{selected_user.email}}">
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="user_id" value={{selected_user.id}}>
                        <input type="hidden" name="update_user" value=1>
                        <button class="mt-2 btn btn-primary">Actualizar Usuario</button>
                    </form>
                </div>

                <form method="POST" action="{% url 'company_detail' company.id %}" style="position: absolute; right: 0; top: 10px;">
                    {% csrf_token %} 
                    <button class="mb-2 mr-2 btn btn-success">&#8592; &nbsp; Volver</button>
                    <input type="hidden" name="action" value="select">
                    <input type="hidden" name="company" value={{company.id}}>
                </form>
            </div>
        </div>
    </div>
</div>
<script>


</script>
{% endblock%}