dpe_app/urls.py
"""dpe_app URL Configuration"""
#Django.
from django.contrib import admin
from django.urls import path, include
#Apps.
from dpe_app import views as dpe_views
from company import views as company_views
from company import views as company_views
from tests import views as tests_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('users/',include(('users.urls','users'), namespace='users')),
    path('company/',include(('company.urls','company'), namespace='company')),
    path('tests/', include('tests.urls')),
    path(
        route='dsh', 
        view=dpe_views.dashboard, 
        name='dashboard'
    ),
    path(
        route='cmp', 
        view=company_views.company_list, 
        name='companies'
    ),
    path(
        route='cmp/dtl/<company_id>/', 
        view=company_views.company_detail, 
        name='company_detail'
    ),
    path(
        route='cmp/dtl/<company_id>/<tab>', 
        view=company_views.company_detail, 
        name='company_detail'
    ),
    path(
        route='pstn',
        view=dpe_views.position_list,
        name='positions'
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path(
        route='',
        view=views.login_view, 
        name='login'
    ),
    path(
        route='admn',
        view=views.users_adm,
        name='users_admn'
    ),
    path(
        route='logout',
        view=views.log_out, 
        name='logout'
    ),
]

templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block content_title %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script src="sweetalert2.all.min.js"></script>
    <!-- Optional: include a polyfill for ES6 Promises for IE11 -->
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>


</head>
<body>
    <body>
        <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
            <div class="app-header header-shadow" >
                <div class="app-header__logo">
                    <div>
                        <img src='{% static "images/logo_color.jpeg" %}' alt="dpe_logo_color" srcset="" style="height: 60px;">
                    </div>
                    <div class="header__pane ml-auto">

                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                        <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
                </div>    <div class="app-header__content">
                    <div class="app-header-left">
      
                    </div>
                    <div class="app-header-right">
                        <div class="header-btn-lg pr-0">
                            <div class="widget-content p-0">
                                <div class="widget-content-wrapper">
                                    <div class="widget-content-left">
                                        <div id="user-options-id" class="btn-group show">
                                            <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" class="p-0 btn">
                                                <i class="fas fa-user-circle rounded-circle" style="width: 45px; font-size: 35px;"></i>
                                                <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                            </a>
                                            <div id="user-options-menu-id" tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-180px, 44px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                <a href="{% url 'users:logout' %}" tabindex="0" class="dropdown-item">Salir</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="widget-content-left  ml-3 header-user-info">
                                        <div class="widget-heading">
                                            {{user.first_name}}
                                        </div>
                                        <div class="widget-subheading">
                                            {%if user.type == "ADMIN_DPE"%} Administrador DPE {% endif %}
                                            {%if user.type == "CLIENT_MAIN"%} Cliente Matriz {% endif %}
                                            {%if user.type == "CLIENT"%} Cliente Sub {% endif %}
                                        </div>
                                    </div>
                                    <div class="widget-content-right header-user-info ml-3">
                                        <button type="button" class="btn-shadow p-1 btn btn-primary btn-sm show-toastr-example">
                                            <i class="fa text-white fa-calendar pr-1 pl-1"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>        
                    </div>
                </div>
            </div>        
            <div class="app-main">
                    <div class="app-sidebar sidebar-shadow sidebar-text-light bg-midnight-bloom">
                        <div class="app-header__logo">
                            <div class="logo-src"></div>
                            <div class="header__pane ml-auto">
                                <div>
                                    <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                                        <span class="hamburger-box">
                                            <span class="hamburger-inner"></span>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="app-header__mobile-menu">
                            <div>
                                <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                            </div>
                        </div>
                        <div class="app-header__menu">
                            <span>
                                <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                    <span class="btn-icon-wrapper">
                                        <i class="fa fa-ellipsis-v fa-w-6"></i>
                                    </span>
                                </button>
                            </span>
                        </div>    
                        <div class="scrollbar-sidebar">
                            <div class="app-sidebar__inner">
                                <ul class="vertical-nav-menu">
                                    <li class="app-sidebar__heading">DPE</li>
                                    <li>
                                        <a href="{% url 'dashboard' %}">
                                            <i class="fas fa-chart-line metismenu-icon"></i>
                                            Dashboard
                                        </a>
                                    </li>
                                    <li class="app-sidebar__heading">Administracion</li>
                                    <li>
                                        <a href="#" >
                                            <i class="fas fa-chart-pie metismenu-icon"></i>
                                            Psicometria
                                        </a>
                                        <ul>
                                            <li>
                                                <a href="{% url 'companies' %}">
                                                    <i class="metismenu-icon"></i>
                                                    Empresas
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    {% comment %} Only dpe admin are allowed to the next section {% endcomment %}
                                    {% if user.type == 'ADMIN_DPE'%}
                                        <li class="app-sidebar__heading">Sistema</li>
                                        <li>
                                            <a href="{% url 'users:users_admn' %}" >
                                            {% comment %} class="mm-active" {% endcomment %}
                                                <i class="fas fa-user-cog metismenu-icon"></i>
                                                Usuarios
                                            </a>
                                            <a href="{% url 'admin:index' %}">
                                                <i class="fas fa-database metismenu-icon"></i> 
                                                Panel de control
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>    
                    <div class="app-main__outer">
                        <div class="app-main__inner">

                            {% block content_subtitle %} {% endblock %}


                                       
                                
                                {% block content_container %} {% endblock %}


                            
                            
                            
                        <div class="app-wrapper-footer">
                            <div class="app-footer">
                                <div class="app-footer__inner">
                                    <div class="app-footer-left">
                                        <ul class="nav">    
                                            <li class="nav-item">
                                                <a href="javascript:void(0);" class="nav-link">
                                                    DPE Corp. 2020 ver. 0
                                                </a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                    <div class="app-footer-right">
                                        <ul class="nav">    
                                            <li class="nav-item">
                                                <a href="javascript:void(0);" class="nav-link" onclick="showContactInfo()">
                                                    Comunicate con nosotros
                                                </a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>    
                    </div>
            </div>
        </div>
    </body>

    <script>
        document.addEventListener("DOMContentLoaded", e => {
            setListeners();
        })
        // Listeners for the top menu actions
        function setListeners(){
            option_menu_div = document.getElementById('user-options-id');
            option_menu_div.addEventListener('click', e => {
                console.log('clicked menu')
                option_menu = document.getElementById('user-options-menu-id');
                option_menu.classList.toggle('show');
            })
        }

        function showContactInfo(){
            Swal.fire({
                title: '<H3>Comunicate con nosotros</H3>',
                icon: 'info',
                html:
                    ' <b>Telefono:&nbsp;</b> 5556041301 <br><br>' +
                    ' <b>Whatsapp:&nbsp;</b> 5569658667 <br><br>' +
                    ' <b>Email:&nbsp;</b> mariantonietadpe@dpeassess.com <br><br>' +
                    ' O visita nuestra pagina web <br><br>' +
                    '<a href="https://www.dpecorp.com.mx/">DPE Corp</a> <br>',
            })
        }
        // To show a sweet alert anywhere, just call it
        function showSwal(icon,title,text,footer) {
            Swal.fire({
                    icon: icon,
                    title: title,
                    text: text,
                    footer: footer
                })
        }
    </script>
</html>